///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AnotherTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AnotherTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b579d100-46b0-46ca-ac5f-81a37cdfa544")]
    public partial class AnotherTestRepository : RepoGenBaseFolder
    {
        static AnotherTestRepository instance = new AnotherTestRepository();
        AnotherTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        AnotherTestRepositoryFolders.DMEMeshAppFolder _dmemesh;

        /// <summary>
        /// Gets the singleton class instance representing the AnotherTestRepository element repository.
        /// </summary>
        [RepositoryFolder("b579d100-46b0-46ca-ac5f-81a37cdfa544")]
        public static AnotherTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AnotherTestRepository() 
            : base("AnotherTestRepository", "/", null, 0, false, "b579d100-46b0-46ca-ac5f-81a37cdfa544", ".\\RepositoryImages\\AnotherTestRepositoryb579d100.rximgres")
        {
            _applicationundertest = new AnotherTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _dmemesh = new AnotherTestRepositoryFolders.DMEMeshAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b579d100-46b0-46ca-ac5f-81a37cdfa544")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("5b289a17-f8e1-4562-8a31-77720c082f1a")]
        public virtual AnotherTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The DMEMesh folder.
        /// </summary>
        [RepositoryFolder("0a6ec82f-5288-44ef-b8d1-55682690c4fc")]
        public virtual AnotherTestRepositoryFolders.DMEMeshAppFolder DMEMesh
        {
            get { return _dmemesh; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AnotherTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("5b289a17-f8e1-4562-8a31-77720c082f1a")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            AnotherTestRepositoryFolders.Jss33Folder _jss33;
            RepoItemInfo _accountsInfo;
            RepoItemInfo _administrationInfo;
            RepoItemInfo _currenciessidebarlinkInfo;
            RepoItemInfo _assettokensInfo;
            RepoItemInfo _systemInfo;
            RepoItemInfo _operationsInfo;
            RepoItemInfo _httpsstoragegoogleapiscommeshdevInfo;
            RepoItemInfo _appbarlogoutInfo;
            RepoItemInfo _rootInfo;
            RepoItemInfo _dashboardInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='dev.mesh.trade']", parentFolder, 30000, null, false, "5b289a17-f8e1-4562-8a31-77720c082f1a", "")
            {
                _jss33 = new AnotherTestRepositoryFolders.Jss33Folder(this);
                _accountsInfo = new RepoItemInfo(this, "Accounts", ".//div[#'accounts-sidebar-link']/?/?/span[@innertext='Accounts']", 30000, null, "00f1b59d-065e-4114-87af-28a8ee348d02");
                _administrationInfo = new RepoItemInfo(this, "Administration", ".//div[#'administration-sidebar-link']/?/?/span[@innertext='Administration']", 30000, null, "31b1ed78-6a08-43df-9f77-51af75343ed9");
                _currenciessidebarlinkInfo = new RepoItemInfo(this, "CurrenciesSidebarLink", ".//div[#'currencies-sidebar-link']", 30000, null, "d7e7cfa2-8f02-483d-be28-575abe3e4b19");
                _assettokensInfo = new RepoItemInfo(this, "AssetTokens", ".//div[#'asset-tokens-sidebar-link']/?/?/span[@innertext='Asset Tokens']", 30000, null, "9fc007b7-a16e-4be3-b80f-1b340d0be44b");
                _systemInfo = new RepoItemInfo(this, "System", ".//div[#'system-sidebar-link']/?/?/span[@innertext='System']", 30000, null, "9d731b15-7d54-4bfd-91c4-646e8c6747ca");
                _operationsInfo = new RepoItemInfo(this, "Operations", ".//div[#'operations-sidebar-link']/?/?/span[@innertext='Operations']", 30000, null, "157a14cb-dbb0-4c8a-8811-7e83fdf9306b");
                _httpsstoragegoogleapiscommeshdevInfo = new RepoItemInfo(this, "HttpsStorageGoogleapisComMeshDev", ".//button[#'appBar-avatar']//img[@alt='']", 30000, null, "c66a780b-521d-41b3-b8e9-4c5117ab95a8");
                _appbarlogoutInfo = new RepoItemInfo(this, "AppBarLogout", ".//li[#'appBar-logout']", 30000, null, "42d718bf-200a-4220-9918-f76b8a6b7f91");
                _rootInfo = new RepoItemInfo(this, "Root", ".//div[#'root']", 30000, null, "4c33440d-9cd7-4175-9e9c-94579bb3bcb4");
                _dashboardInfo = new RepoItemInfo(this, "Dashboard", ".//div[#'dashboard-sidebar-link']/?/?/span[@innertext='Dashboard']", 30000, null, "6f069aae-00a4-462d-8c67-a0633c8181f1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5b289a17-f8e1-4562-8a31-77720c082f1a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5b289a17-f8e1-4562-8a31-77720c082f1a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Accounts item.
            /// </summary>
            [RepositoryItem("00f1b59d-065e-4114-87af-28a8ee348d02")]
            public virtual Ranorex.SpanTag Accounts
            {
                get
                {
                    return _accountsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Accounts item info.
            /// </summary>
            [RepositoryItemInfo("00f1b59d-065e-4114-87af-28a8ee348d02")]
            public virtual RepoItemInfo AccountsInfo
            {
                get
                {
                    return _accountsInfo;
                }
            }

            /// <summary>
            /// The Administration item.
            /// </summary>
            [RepositoryItem("31b1ed78-6a08-43df-9f77-51af75343ed9")]
            public virtual Ranorex.SpanTag Administration
            {
                get
                {
                    return _administrationInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Administration item info.
            /// </summary>
            [RepositoryItemInfo("31b1ed78-6a08-43df-9f77-51af75343ed9")]
            public virtual RepoItemInfo AdministrationInfo
            {
                get
                {
                    return _administrationInfo;
                }
            }

            /// <summary>
            /// The CurrenciesSidebarLink item.
            /// </summary>
            [RepositoryItem("d7e7cfa2-8f02-483d-be28-575abe3e4b19")]
            public virtual Ranorex.DivTag CurrenciesSidebarLink
            {
                get
                {
                    return _currenciessidebarlinkInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CurrenciesSidebarLink item info.
            /// </summary>
            [RepositoryItemInfo("d7e7cfa2-8f02-483d-be28-575abe3e4b19")]
            public virtual RepoItemInfo CurrenciesSidebarLinkInfo
            {
                get
                {
                    return _currenciessidebarlinkInfo;
                }
            }

            /// <summary>
            /// The AssetTokens item.
            /// </summary>
            [RepositoryItem("9fc007b7-a16e-4be3-b80f-1b340d0be44b")]
            public virtual Ranorex.SpanTag AssetTokens
            {
                get
                {
                    return _assettokensInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AssetTokens item info.
            /// </summary>
            [RepositoryItemInfo("9fc007b7-a16e-4be3-b80f-1b340d0be44b")]
            public virtual RepoItemInfo AssetTokensInfo
            {
                get
                {
                    return _assettokensInfo;
                }
            }

            /// <summary>
            /// The System item.
            /// </summary>
            [RepositoryItem("9d731b15-7d54-4bfd-91c4-646e8c6747ca")]
            public virtual Ranorex.SpanTag System
            {
                get
                {
                    return _systemInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The System item info.
            /// </summary>
            [RepositoryItemInfo("9d731b15-7d54-4bfd-91c4-646e8c6747ca")]
            public virtual RepoItemInfo SystemInfo
            {
                get
                {
                    return _systemInfo;
                }
            }

            /// <summary>
            /// The Operations item.
            /// </summary>
            [RepositoryItem("157a14cb-dbb0-4c8a-8811-7e83fdf9306b")]
            public virtual Ranorex.SpanTag Operations
            {
                get
                {
                    return _operationsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Operations item info.
            /// </summary>
            [RepositoryItemInfo("157a14cb-dbb0-4c8a-8811-7e83fdf9306b")]
            public virtual RepoItemInfo OperationsInfo
            {
                get
                {
                    return _operationsInfo;
                }
            }

            /// <summary>
            /// The HttpsStorageGoogleapisComMeshDev item.
            /// </summary>
            [RepositoryItem("c66a780b-521d-41b3-b8e9-4c5117ab95a8")]
            public virtual Ranorex.ImgTag HttpsStorageGoogleapisComMeshDev
            {
                get
                {
                    return _httpsstoragegoogleapiscommeshdevInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsStorageGoogleapisComMeshDev item info.
            /// </summary>
            [RepositoryItemInfo("c66a780b-521d-41b3-b8e9-4c5117ab95a8")]
            public virtual RepoItemInfo HttpsStorageGoogleapisComMeshDevInfo
            {
                get
                {
                    return _httpsstoragegoogleapiscommeshdevInfo;
                }
            }

            /// <summary>
            /// The AppBarLogout item.
            /// </summary>
            [RepositoryItem("42d718bf-200a-4220-9918-f76b8a6b7f91")]
            public virtual Ranorex.LiTag AppBarLogout
            {
                get
                {
                    return _appbarlogoutInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The AppBarLogout item info.
            /// </summary>
            [RepositoryItemInfo("42d718bf-200a-4220-9918-f76b8a6b7f91")]
            public virtual RepoItemInfo AppBarLogoutInfo
            {
                get
                {
                    return _appbarlogoutInfo;
                }
            }

            /// <summary>
            /// The Root item.
            /// </summary>
            [RepositoryItem("4c33440d-9cd7-4175-9e9c-94579bb3bcb4")]
            public virtual Ranorex.DivTag Root
            {
                get
                {
                    return _rootInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Root item info.
            /// </summary>
            [RepositoryItemInfo("4c33440d-9cd7-4175-9e9c-94579bb3bcb4")]
            public virtual RepoItemInfo RootInfo
            {
                get
                {
                    return _rootInfo;
                }
            }

            /// <summary>
            /// The Dashboard item.
            /// </summary>
            [RepositoryItem("6f069aae-00a4-462d-8c67-a0633c8181f1")]
            public virtual Ranorex.SpanTag Dashboard
            {
                get
                {
                    return _dashboardInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Dashboard item info.
            /// </summary>
            [RepositoryItemInfo("6f069aae-00a4-462d-8c67-a0633c8181f1")]
            public virtual RepoItemInfo DashboardInfo
            {
                get
                {
                    return _dashboardInfo;
                }
            }

            /// <summary>
            /// The Jss33 folder.
            /// </summary>
            [RepositoryFolder("65f3bfb2-136a-4a0f-a740-417be59132ff")]
            public virtual AnotherTestRepositoryFolders.Jss33Folder Jss33
            {
                get { return _jss33; }
            }
        }

        /// <summary>
        /// The Jss33Folder folder.
        /// </summary>
        [RepositoryFolder("65f3bfb2-136a-4a0f-a740-417be59132ff")]
        public partial class Jss33Folder : RepoGenBaseFolder
        {
            RepoItemInfo _accountmanagementInfo;
            RepoItemInfo _webelementsvg4Info;
            RepoItemInfo _webelementsvg5Info;
            RepoItemInfo _viewInfo;
            RepoItemInfo _webelementsvgInfo;
            RepoItemInfo _webelementsvg1Info;
            RepoItemInfo _muibuttonbaserootmuibuttoncontainedmInfo;
            RepoItemInfo _pathInfo;
            RepoItemInfo _path1Info;
            RepoItemInfo _webelementsvg2Info;
            RepoItemInfo _webelementsvg3Info;
            RepoItemInfo _jss51Info;

            /// <summary>
            /// Creates a new Jss33  folder.
            /// </summary>
            public Jss33Folder(RepoGenBaseFolder parentFolder) :
                    base("Jss33", ".//div[#'root']/div/div/div[2]/div[2]/div[2]", parentFolder, 30000, null, false, "65f3bfb2-136a-4a0f-a740-417be59132ff", "")
            {
                _accountmanagementInfo = new RepoItemInfo(this, "AccountManagement", ".//span[@innertext='Account Management >']", 30000, null, "b6e642dc-d61e-46fc-80e4-6d940eb1d33d");
                _webelementsvg4Info = new RepoItemInfo(this, "WebElementSvg4", "div/div/div[2]/div[10]/?/?/button/?/?/tag[@tagname='svg']", 30000, null, "740f9e97-3314-4aac-9467-56268bdeb716");
                _webelementsvg5Info = new RepoItemInfo(this, "WebElementSvg5", "div/div/div[2]/div[10]/?/?/button/span[1]/tag[@tagname='svg']", 30000, null, "c29f0d1d-f48f-4d83-abcd-a7e063ebc012");
                _viewInfo = new RepoItemInfo(this, "View", "div/div/div[2]/div[10]/div[1]/div[4]//span[@innertext='View']", 30000, null, "b7ae3b5e-bf12-42cc-ae29-f06ac3703c23");
                _webelementsvgInfo = new RepoItemInfo(this, "WebElementSvg", "div/div/div[2]/div[2]/?/?/button/?/?/tag[@tagname='svg']", 30000, null, "03435358-fcca-4c5c-9a6d-f62c3b58fc66");
                _webelementsvg1Info = new RepoItemInfo(this, "WebElementSvg1", "div/div/div[2]/div[4]/?/?/button/?/?/tag[@tagname='svg']", 30000, null, "1a503fae-55a3-4c3f-82e5-806c2caa0d87");
                _muibuttonbaserootmuibuttoncontainedmInfo = new RepoItemInfo(this, "MuiButtonBaseRootMuiButtonContainedM", "div/div/div[2]/div[4]/div[1]/div[4]//button", 30000, null, "c7fc4ca2-8b1b-408d-8cbf-aaf63c45b33d");
                _pathInfo = new RepoItemInfo(this, "Path", "div/div/div[2]/div[6]/?/?/button//tag[@tagname='path']", 30000, null, "2d2c3f7a-df7d-4983-82f7-a7944be75a97");
                _path1Info = new RepoItemInfo(this, "Path1", "div/div/div[2]/div[6]/?/?/button/span[1]/tag[@tagname='svg']/tag", 30000, null, "afb5b606-cb76-427e-aef0-de2f0f91bd74");
                _webelementsvg2Info = new RepoItemInfo(this, "WebElementSvg2", "div/div/div[2]/div[8]/?/?/button/?/?/tag[@tagname='svg']", 30000, null, "f4871ad5-bc4d-4a82-b434-d6535784f978");
                _webelementsvg3Info = new RepoItemInfo(this, "WebElementSvg3", "div/div/div[2]/div[8]/?/?/button/span[1]/tag[@tagname='svg']", 30000, null, "0b085e05-58a7-4493-b478-b8cda2dcbb6d");
                _jss51Info = new RepoItemInfo(this, "Jss51", "div/div/div[2]", 30000, null, "b3171e2b-e3fa-4240-93c2-e7cac8a3e39b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("65f3bfb2-136a-4a0f-a740-417be59132ff")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("65f3bfb2-136a-4a0f-a740-417be59132ff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AccountManagement item.
            /// </summary>
            [RepositoryItem("b6e642dc-d61e-46fc-80e4-6d940eb1d33d")]
            public virtual Ranorex.SpanTag AccountManagement
            {
                get
                {
                    return _accountmanagementInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AccountManagement item info.
            /// </summary>
            [RepositoryItemInfo("b6e642dc-d61e-46fc-80e4-6d940eb1d33d")]
            public virtual RepoItemInfo AccountManagementInfo
            {
                get
                {
                    return _accountmanagementInfo;
                }
            }

            /// <summary>
            /// The WebElementSvg4 item.
            /// </summary>
            [RepositoryItem("740f9e97-3314-4aac-9467-56268bdeb716")]
            public virtual Ranorex.WebElement WebElementSvg4
            {
                get
                {
                    return _webelementsvg4Info.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The WebElementSvg4 item info.
            /// </summary>
            [RepositoryItemInfo("740f9e97-3314-4aac-9467-56268bdeb716")]
            public virtual RepoItemInfo WebElementSvg4Info
            {
                get
                {
                    return _webelementsvg4Info;
                }
            }

            /// <summary>
            /// The WebElementSvg5 item.
            /// </summary>
            [RepositoryItem("c29f0d1d-f48f-4d83-abcd-a7e063ebc012")]
            public virtual Ranorex.WebElement WebElementSvg5
            {
                get
                {
                    return _webelementsvg5Info.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The WebElementSvg5 item info.
            /// </summary>
            [RepositoryItemInfo("c29f0d1d-f48f-4d83-abcd-a7e063ebc012")]
            public virtual RepoItemInfo WebElementSvg5Info
            {
                get
                {
                    return _webelementsvg5Info;
                }
            }

            /// <summary>
            /// The View item.
            /// </summary>
            [RepositoryItem("b7ae3b5e-bf12-42cc-ae29-f06ac3703c23")]
            public virtual Ranorex.SpanTag View
            {
                get
                {
                    return _viewInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The View item info.
            /// </summary>
            [RepositoryItemInfo("b7ae3b5e-bf12-42cc-ae29-f06ac3703c23")]
            public virtual RepoItemInfo ViewInfo
            {
                get
                {
                    return _viewInfo;
                }
            }

            /// <summary>
            /// The WebElementSvg item.
            /// </summary>
            [RepositoryItem("03435358-fcca-4c5c-9a6d-f62c3b58fc66")]
            public virtual Ranorex.WebElement WebElementSvg
            {
                get
                {
                    return _webelementsvgInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The WebElementSvg item info.
            /// </summary>
            [RepositoryItemInfo("03435358-fcca-4c5c-9a6d-f62c3b58fc66")]
            public virtual RepoItemInfo WebElementSvgInfo
            {
                get
                {
                    return _webelementsvgInfo;
                }
            }

            /// <summary>
            /// The WebElementSvg1 item.
            /// </summary>
            [RepositoryItem("1a503fae-55a3-4c3f-82e5-806c2caa0d87")]
            public virtual Ranorex.WebElement WebElementSvg1
            {
                get
                {
                    return _webelementsvg1Info.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The WebElementSvg1 item info.
            /// </summary>
            [RepositoryItemInfo("1a503fae-55a3-4c3f-82e5-806c2caa0d87")]
            public virtual RepoItemInfo WebElementSvg1Info
            {
                get
                {
                    return _webelementsvg1Info;
                }
            }

            /// <summary>
            /// The MuiButtonBaseRootMuiButtonContainedM item.
            /// </summary>
            [RepositoryItem("c7fc4ca2-8b1b-408d-8cbf-aaf63c45b33d")]
            public virtual Ranorex.ButtonTag MuiButtonBaseRootMuiButtonContainedM
            {
                get
                {
                    return _muibuttonbaserootmuibuttoncontainedmInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The MuiButtonBaseRootMuiButtonContainedM item info.
            /// </summary>
            [RepositoryItemInfo("c7fc4ca2-8b1b-408d-8cbf-aaf63c45b33d")]
            public virtual RepoItemInfo MuiButtonBaseRootMuiButtonContainedMInfo
            {
                get
                {
                    return _muibuttonbaserootmuibuttoncontainedmInfo;
                }
            }

            /// <summary>
            /// The Path item.
            /// </summary>
            [RepositoryItem("2d2c3f7a-df7d-4983-82f7-a7944be75a97")]
            public virtual Ranorex.WebElement Path
            {
                get
                {
                    return _pathInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Path item info.
            /// </summary>
            [RepositoryItemInfo("2d2c3f7a-df7d-4983-82f7-a7944be75a97")]
            public virtual RepoItemInfo PathInfo
            {
                get
                {
                    return _pathInfo;
                }
            }

            /// <summary>
            /// The Path1 item.
            /// </summary>
            [RepositoryItem("afb5b606-cb76-427e-aef0-de2f0f91bd74")]
            public virtual Ranorex.WebElement Path1
            {
                get
                {
                    return _path1Info.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Path1 item info.
            /// </summary>
            [RepositoryItemInfo("afb5b606-cb76-427e-aef0-de2f0f91bd74")]
            public virtual RepoItemInfo Path1Info
            {
                get
                {
                    return _path1Info;
                }
            }

            /// <summary>
            /// The WebElementSvg2 item.
            /// </summary>
            [RepositoryItem("f4871ad5-bc4d-4a82-b434-d6535784f978")]
            public virtual Ranorex.WebElement WebElementSvg2
            {
                get
                {
                    return _webelementsvg2Info.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The WebElementSvg2 item info.
            /// </summary>
            [RepositoryItemInfo("f4871ad5-bc4d-4a82-b434-d6535784f978")]
            public virtual RepoItemInfo WebElementSvg2Info
            {
                get
                {
                    return _webelementsvg2Info;
                }
            }

            /// <summary>
            /// The WebElementSvg3 item.
            /// </summary>
            [RepositoryItem("0b085e05-58a7-4493-b478-b8cda2dcbb6d")]
            public virtual Ranorex.WebElement WebElementSvg3
            {
                get
                {
                    return _webelementsvg3Info.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The WebElementSvg3 item info.
            /// </summary>
            [RepositoryItemInfo("0b085e05-58a7-4493-b478-b8cda2dcbb6d")]
            public virtual RepoItemInfo WebElementSvg3Info
            {
                get
                {
                    return _webelementsvg3Info;
                }
            }

            /// <summary>
            /// The Jss51 item.
            /// </summary>
            [RepositoryItem("b3171e2b-e3fa-4240-93c2-e7cac8a3e39b")]
            public virtual Ranorex.DivTag Jss51
            {
                get
                {
                    return _jss51Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Jss51 item info.
            /// </summary>
            [RepositoryItemInfo("b3171e2b-e3fa-4240-93c2-e7cac8a3e39b")]
            public virtual RepoItemInfo Jss51Info
            {
                get
                {
                    return _jss51Info;
                }
            }
        }

        /// <summary>
        /// The DMEMeshAppFolder folder.
        /// </summary>
        [RepositoryFolder("0a6ec82f-5288-44ef-b8d1-55682690c4fc")]
        public partial class DMEMeshAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btngoogleInfo;
            RepoItemInfo _divtagsignInfo;

            /// <summary>
            /// Creates a new DMEMesh  folder.
            /// </summary>
            public DMEMeshAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DMEMesh", "/dom[@domain='andile.eu.auth0.com']", parentFolder, 30000, null, false, "0a6ec82f-5288-44ef-b8d1-55682690c4fc", "")
            {
                _btngoogleInfo = new RepoItemInfo(this, "BtnGoogle", ".//div[#'btn-google']", 30000, null, "47909358-8539-4e65-b8c8-2b9801ad8be4");
                _divtagsignInfo = new RepoItemInfo(this, "DivTagSign", ".//div[#'btn-google']/div[2]", 30000, null, "9aa6a8c9-6109-4d92-b826-8ee8b012c7a5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0a6ec82f-5288-44ef-b8d1-55682690c4fc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0a6ec82f-5288-44ef-b8d1-55682690c4fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnGoogle item.
            /// </summary>
            [RepositoryItem("47909358-8539-4e65-b8c8-2b9801ad8be4")]
            public virtual Ranorex.DivTag BtnGoogle
            {
                get
                {
                    return _btngoogleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BtnGoogle item info.
            /// </summary>
            [RepositoryItemInfo("47909358-8539-4e65-b8c8-2b9801ad8be4")]
            public virtual RepoItemInfo BtnGoogleInfo
            {
                get
                {
                    return _btngoogleInfo;
                }
            }

            /// <summary>
            /// The DivTagSign item.
            /// </summary>
            [RepositoryItem("9aa6a8c9-6109-4d92-b826-8ee8b012c7a5")]
            public virtual Ranorex.DivTag DivTagSign
            {
                get
                {
                    return _divtagsignInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagSign item info.
            /// </summary>
            [RepositoryItemInfo("9aa6a8c9-6109-4d92-b826-8ee8b012c7a5")]
            public virtual RepoItemInfo DivTagSignInfo
            {
                get
                {
                    return _divtagsignInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
