///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AnotherTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("fa3e0d55-735e-41f4-83cd-675911f007ac", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AnotherTestRepository repository.
        /// </summary>
        public static AnotherTestRepository repo = AnotherTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DMEMesh.DivTagSign' at 43;4.", repo.DMEMesh.DivTagSignInfo, new RecordItemIndex(0));
            repo.DMEMesh.DivTagSign.Click("43;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 111;154.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Self.Click("111;154");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Accounts' at 45;5.", repo.ApplicationUnderTest.AccountsInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Accounts.Click("45;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Administration' at 49;2.", repo.ApplicationUnderTest.AdministrationInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Administration.Click("49;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CurrenciesSidebarLink' at 119;5.", repo.ApplicationUnderTest.CurrenciesSidebarLinkInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.CurrenciesSidebarLink.Click("119;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AssetTokens' at 46;4.", repo.ApplicationUnderTest.AssetTokensInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.AssetTokens.Click("46;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.System' at 48;6.", repo.ApplicationUnderTest.SystemInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.System.Click("48;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Operations' at 49;1.", repo.ApplicationUnderTest.OperationsInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Operations.Click("49;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsStorageGoogleapisComMeshDev' at 31;21.", repo.ApplicationUnderTest.HttpsStorageGoogleapisComMeshDevInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.HttpsStorageGoogleapisComMeshDev.Click("31;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AppBarLogout' at 52;11.", repo.ApplicationUnderTest.AppBarLogoutInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.AppBarLogout.Click("52;11");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
